# Copy Mongodb yaml repo
- name: Copy Mongodb Yum Repo File
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

# INSTALL Mongodb yum repo
- name: Install yum repo
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

# Change IP 127.0.0.1 to 0.0.0.0 in config file
- name: Change IP
  ansible.builtin.replace:
    path: /etc/mongodb.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'