- name: Create roboshop parameters
  hosts: localhost
  tasks:
    - name: create value
      community.aws.aws_ssm_parameter_store:
        name: "{{item.name}}"
        value: "{{item.value}}"
        region: "us-east-1"
      loop:
        - {name: "param_dev_catalogue_MONGO" , value: "true"}
        - {name: "param_dev_user_MONGO" , value: "true"}