- name: Create roboshop parameters
  hosts: localhost
  tasks:
    - name: create value
      community.aws.aws_ssm_parameter_store:
        name: param_dev_catalogue_mongo
        value: "false"
        region: "us-east-1"