#- name: tests for frontend
  #debug:
    #msg: frontend

# Install Nginx
- name: Install Nginx # install nginx
  ansible.builtin.yum:
    name: nginx # this name of package
    state: installed


# Include role
- name: Include Download app code tasks from Common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download-app-code

# copy roboshop conf file
- name: Copy Roboshop Configuration file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Start nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

