#- name: tests for frontend
  #debug:
    #msg: frontend

# Install Nginx
- name: Install Nginx # install nginx
  ansible.builtin.yum:
    name: nginx # this name of package
    state: installed

- name: Include Download app code tasks from common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download-app-code