#- name: tests for frontend
  #debug:
    #msg: frontend

# Install Nginx
- name: Install Nginx # install nginx
  ansible.builtin.yum:
    name: nginx # this name of package
    state: installed


# Include role
- name: Include Download app code tasks from Common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download-app-code

# create a directory
- name: Create a directory if it does not exist
  ansible.builtin.file:
  path: "{{ APP_LOC }}"
  state: directory

