#- name: tests for frontend
  #debug:
    #msg: frontend

# Install Nginx
- name: Install Nginx # install nginx
  ansible.builtin.yum:
    name: nginx # this name of package
    state: installed


# Include role
- name: Include Download app code tasks from Common role
  ansible.builtin.include_role:
    name: common
    tasks_from: download-app-code

# Remove previous version of app
- name: Recursively remove directory
  ansible.builtin.file:
  path: "{{APP_LOC}}" # Here it is going remove the previous version of app
  state: absent

# unarchive a file
- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: "{{APP_LOC}}"
    remote_src: yes