# create an application user

- name: Create an application USER
  when: APP_USER is defined
  ansible.builtin.debug:
  USER:
    name: "{{APP_USER}}"

- name: Download APP Content
  ansible.builtin.get_url:
    URL: https://github.com/roboshop-devops-project/${{ COMPONENT }}/archive/main.zip
    dest: /tmp/${{ COMPONENT }}.zip
