# create an application user
- name: Create an application USER
  when: APP_USER is defined
  ansible.builtin.user:
    name: "{{APP_USER}}"

- name: Download APP Content
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: /tmp/{{ COMPONENT }}.zip

# Remove previous version of app
- name: Recursively remove directory
  ansible.builtin.file:
    path: "{{ APP_LOC }}"
    state: absent

# unarchive a file
- name: Download app content & extract it
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/{{ COMPONENT }}/archive/main.zip
    dest: "{{ APP_LOC }}"
    remote_src: yes

