- name: Load Schema
  community.mongodb.mongodb_shell:
    login_host: "{{ lookup('aws_ssm', 'param_{{ENV}}_catalogue_MONGO_ENDPOINT', region='us-east-1' ) }}"
    file: "{{APP_LOC}}/schema/{{COMPONENT}}.js"
    idempotent: yes

