#  SYSTEMD_SETUP() {
#    PRINT "Configure Endpoints for SystemD Configuration"
#    sed -i -e 's/MONGO_DNSNAME/dev-mongodb.sarbjeet310.online/' -e 's/REDIS_ENDPOINT/dev-redis.sarbjeet310.online/' -e 's/CATALOGUE_ENDPOINT/dev-catalogue.sarbjeet310.online/' -e 's/MONGO_ENDPOINT/dev-mongodb.sarbjeet310.online/' -e 's/CARTENDPOINT/dev-cart.sarbjeet310.online/' -e 's/DBHOST/dev-mysql.sarbjeet310.online/' -e 's/AMQPHOST/dev-rabbitmq.sarbjeet310.online/' -e 's/CARTHOST/dev-cart.sarbjeet310.online/' -e 's/USERHOST/dev-user.sarbjeet310.online/' /home/roboshop/${COMPONENT}/systemd.service &>>$LOG
#    mv /home/roboshop/${COMPONENT}/systemd.service /etc/systemd/system/${COMPONENT}.service
#    STAT $?
#
#    PRINT "Restart ${COMPONENT}"
#    systemctl daemon-reload &>>$LOG && systemctl restart ${COMPONENT} &>>$LOG && systemctl enable ${COMPONENT} &>>$LOG
#    STAT $?
#  }

- name: Setup systemd service file
  ansible.builtin.copy:
    scr: systemd.service
    dest: /etc/systemd/system/{{ COMPONENT }}.service

- name: start {{ COMPONENT }} service
  ansible.builtin.systemd:
    name: "{{ COMPONENT }}"
    state: restarted
    enabled: yes
    daemon-reload: yes

